env:
    credentials: "ENCRYPTED[!4f83dca9a98003e49cc4a8b38aeb44eaefa9d6c8b1afb7f55248691a390b006e9f4c104c25951b5bbe5e6a58556e4f61!]"
    rcloneconfig: "ENCRYPTED[!46711e650c102b7763b91f869840ea01b1cbb71696e03853b357c74bd66c90b702fe263c5db81648389e07cc1abdf542!]"
    tokentl: "ENCRYPTED[!78df93af52b276deba904023576dbf45df5be7a833cb3a83509bcc6af9981f3a8882bf67dadc2ab4a786279a38f2e390!]"
    idtl: 1002529476463
    lunch: lunch lineage_ginkgo-userdebug
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Wrdn28"
       - git config --global user.email "ifloraxd@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy drive:lineage/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Start sync lineage Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/LineageOS-Revived/android.git -b lineage-17.1 -g default,-mips,-darwin,-notdefault
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/revived.xml
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - git clone https://github.com/Wrdn28/android_device_xiaomi_ginkgo -b 10 device/xiaomi/ginkgo
      - git clone https://github.com/andrraa/vendor_xiaomi_ginkgo -b 10 vendor/xiaomi/ginkgo --depth=1
      - git clone https://github.com/Wrdn28/hyper_kernel_ginkgo -b A10 kernel/xiaomi/ginkgo --depth=1
      - git clone https://github.com/andrraa/android_vendor_miuicamera -b 10 vendor/miuicamera
      - rm -rf hardware/qcom-caf/sm8150/audio && rm -rf hardware/qcom-caf/sm8150/display && rm -rf hardware/qcom-caf/sm8150/media
      - git clone https://github.com/Nusantara-ROM/android_hardware_qcom_display -b 10-sm8150 hardware/qcom-caf/sm8150/display
      - git clone https://github.com/Nusantara-ROM/android_hardware_qcom_media -b 10-sm8150 hardware/qcom-caf/sm8150/media
      - git clone https://github.com/Nusantara-ROM/android_hardware_qcom_audio -b 10-sm8150 hardware/qcom-caf/sm8150/audio 
      - git clone https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/proton-clang --depth=1
      - git clone https://github.com/Wrdn28/keys -b A10 vendor/lineage/signing
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="Hirokixd"
      - export BUILD_HOSTNAME="HKprjkt"
      - export KBUILD_BUILD_USER="Hirokixd"
      - export KBUILD_BUILD_HOST="HKprjkt"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Build lineage for Ginkgo Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Build $(cd ~/rom/out/target/product/ginkgo/ && ls lineage*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz drive:lineage -P
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=-$idtl -d text="Ccache Uploaded Successfully!"
