env:
    credentials: "ENCRYPTED[!5677097f7022272446dbbec68b6c2ab2ceaca4d07845554b961965728d8a123c32e97e6cc64cd832a1bfbd4d0d2bafac!]"
    rcloneconfig: "ENCRYPTED[!713fd1558850e851c870166aa3bca0f65050e06d48b71105b04c5a304e7d297f003de5c221af6ebf2c8301abdf56b93e!]"
    tokentl: "ENCRYPTED[!563b5c0dadf7801ff9978b2930778e68b19c8d0802b669df6d30b004ba151418bafb7b001d594cfc4192fca1bda89082!]"
    idtl: -1002171624083
    lunch: lunch nad_ginkgo-user
    make: make nad

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "Wrdn28"
       - git config --global user.email "ifloraxd@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy hk1:nusantara/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Start sync nusantara Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/S-A-build/android_manifest_nusa -b 10 -g default,-mips,-darwin,-notdefault
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/projects.xml
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - git clone https://github.com/Wrdn28/device_xiaomi_ginkgo-q -b A10 device/xiaomi/ginkgo
      - git clone https://github.com/Wrdn28/vendor_xiaomi_ginkgo-q -b A10 vendor/xiaomi/ginkgo --depth=1
      - git clone https://github.com/Wrdn28/hyper_kernel_ginkgo -b 10 kernel/xiaomi/ginkgo --depth=1
      - git clone https://github.com/andrraa/android_vendor_miuicamera -b 10 vendor/miuicamera
      - git clone https://github.com/kdrag0n/proton-clang -b master prebuilts/clang/host/linux-x86/proton-clang --depth=1
      - rm -rf vendor/qcom/opensource/commonsys/bluetooth_ext
      - git clone https://github.com/LineageOS/android_vendor_qcom_opensource_bluetooth_ext -b lineage-17.1 vendor/qcom/opensource/commonsys/bluetooth_ext
      - sed -i 's| -u||g' vendor/nusantara/config/branding.mk
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="Hirokixd"
      - export BUILD_HOSTNAME="HKprjkt"
      - export KBUILD_BUILD_USER="Hirokixd"
      - export KBUILD_BUILD_HOST="HKprjkt"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Build nusantara for Ginkgo Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Build $(cd ~/rom/out/target/product/ginkgo/ && ls nusantara*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz hk1:nusantara -P
      - curl -s https://api.telegram.org/bot7502875437:AAHWCh1hQ9Wt8X3geAYSKk2T9mtRj8s9ehQ/sendMessage -d chat_id=-1002171624083 -d text="Ccache Uploaded Successfully!"
